### ISSUE TITLE
Use rust-openssl for openssl bindings

### ISSUE THREAD

**Issue by bjorn3** [Thinkofname/steven-rust#31]

**Comment by bjorn3** [comment]
See https://github.com/sfackler/rust-openssl

**Comment by bjorn3** [comment]
Or openssl on crates.io

**Comment by Thinkofname** [comment]
I'm pretty sure the crates are missing the features required for Minecraft's protocol (it does use somewhat old encryption). I've tried to use the crates in the past with little luck

**Comment by bjorn3** [comment]
Which algorithms do you mean?

**Comment by bjorn3** [comment]
There is a ffi lib called openssl-sys which supports (nearly) every openssl function.

**Comment by Thinkofname** [comment]
Most of this block seems to be missing from openssl-sys https://github.com/Thinkofname/steven-rust/blob/master/openssl/src/lib.rs#L45-L54

**Comment by Techcable** [comment]
Whats wrong with the current system?

**Comment by bjorn3** [comment]
Openssl on crates.io supports aes_128_cfb8.

**Comment by Thinkofname** [comment]
hmm it does but seems to use different methods internally to what I use, wonder if that makes a difference

**Comment by bjorn3** [comment]
If you remove the abstractions the only difference as I can see is the init call.

**Comment by Thinkofname** [comment]
I've got it working, the Cipher vs Encrypt/Decrypt methods didn't seem to make a different
