### ISSUE TITLE
AppVeyor artifacts deleted

### ISSUE THREAD

**Issue by dxf** [Thinkofname/steven-rust#72]
Appveyor retention policy deleted them

**Comment by iceiix** [comment]
@Thinkofname Can you share your AppVeyor configuration? Struggling to set it up on my own https://github.com/iceiix/steven/pull/9... stuck on installing OpenSSL dependency on Windows, but once this is solved, should be able to have latest AppVeyor artifacts automatically building again on my branch.

**Comment by Thinkofname** [comment]
```
if "%PLATFORM%" == "x86" set RUST_INSTALL=i686-pc-windows-msvc
if "%PLATFORM%" == "x64" set RUST_INSTALL=x86_64-pc-windows-msvc
appveyor AddMessage "Platform rust: %RUST_INSTALL%"
appveyor DownloadFile "https://static.rust-lang.org/dist/rust-nightly-%RUST_INSTALL%.exe" -FileName rust-install.exe
"./rust-install.exe" /VERYSILENT /NORESTART /DIR="C:\Rust\"
SET PATH=%PATH%;C:\Rust\bin
rustc -V
cargo -V

appveyor DownloadFile http://www.npcglib.org/~stathis/downloads/openssl-1.0.1s-vs2015.7z -FileName openssl.7z
mkdir C:\openssl
7z x openssl.7z -oC:/openssl/ -y
set DEP_OPENSSL_INCLUDE=C:\openssl\openssl-1.0.1s-vs2015\include\
if "%PLATFORM%" == "x64" set OPENSSL_EXT=64
cp C:\openssl\openssl-1.0.1s-vs2015\lib%OPENSSL_EXT%\libeay32MD.lib C:\Rust\lib\rustlib\%RUST_INSTALL%\lib\eay32.lib
cp C:/openssl/openssl-1.0.1s-vs2015/lib%OPENSSL_EXT%\ssleay32MD.lib C:\Rust\lib\rustlib\%RUST_INSTALL%\lib\ssl32.lib

appveyor DownloadFile https://www.libsdl.org/release/SDL2-devel-2.0.4-VC.zip -FileName sdl2-dev.zip
mkdir C:\sdl2
7z x sdl2-dev.zip -oC:\sdl2\ -y
cp C:\sdl2\SDL2-2.0.4\lib\%PLATFORM%\SDL2.lib C:\Rust\lib\rustlib\%RUST_INSTALL%\lib\SDL2.lib

cargo build
mkdir dist-debug
cp target\debug\steven.exe dist-debug
cp C:\sdl2\SDL2-2.0.4\lib\%PLATFORM%\SDL2.dll dist-debug
cp C:\openssl\openssl-1.0.1s-vs2015\bin%OPENSSL_EXT%\libeay32MD.dll dist-debug\libeay32MD.dll
cp C:\openssl\openssl-1.0.1s-vs2015\bin%OPENSSL_EXT%\ssleay32MD.dll dist-debug\ssleay32MD.dll

cargo build --release
mkdir dist
cp target\release\steven.exe dist
cp C:\sdl2\SDL2-2.0.4\lib\%PLATFORM%\SDL2.dll dist
cp C:\openssl\openssl-1.0.1s-vs2015\bin%OPENSSL_EXT%\libeay32MD.dll dist\libeay32MD.dll
cp C:\openssl\openssl-1.0.1s-vs2015\bin%OPENSSL_EXT%\ssleay32MD.dll dist\ssleay32MD.dll
```

**Comment by dxf** [comment]
@Thinkofname please can you force AppVeyor to build again, or put an exe in the cloud for us?

**Comment by Thinkofname** [comment]
I'll trigger one but with the projects current state I don't think it'll build. I don't have an old build hanging around either sorry

**Comment by iceiix** [comment]
https://ci.appveyor.com/project/thinkofdeath/steven-rust/branch/master/job/ujdkv1gpu5mddhjp failed because of a Rust change:

```
154error[E0642]: patterns aren't allowed in methods without bodies
155   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc-serialize-0.3.19\src\serialize.rs:147:45
156    |
157147 |                                             &f_name: &str,
158    |                                             ^^^^^^^
159
160error: aborting due to previous error
161
162For more information about this error, try `rustc --explain E0642`.
163
```

This might be fixable by using nightly-2017-05-14 instead of the latest nightly.

However, with the updates in https://github.com/Thinkofname/steven/pull/75 using  https://github.com/Thinkofname/steven/issues/72#issuecomment-433889692 in my own AppVeyor instance https://ci.appveyor.com/project/iceiix/steven it fails too, not being able to find OpenSSL.

**Comment by iceiix** [comment]
@dxf Changed to use vcpkg to install OpenSSL, got a working Windows .exe build artifact here: https://ci.appveyor.com/project/iceiix/steven/builds/19932661/artifacts - at least it works in my preliminary testing, beware there may be bugs in my update (includes all the changes from https://github.com/Thinkofname/steven/pull/75), but if you find any I'd be interested in reports in my branch (https://github.com/iceiix/steven)

@Thinkofname I think it would be good to check in the AppVeyor configuration so forks can build for Windows easily ("Export YAML" under AppVeyor settings, checked in appveyor.yml). Would you be interested in a pull request to do this? Working on it, but takes a while to test... (~30 min builds).

**Comment by Thinkofname** [comment]
I could but I wasn't really planning to maintain this project anymore, I haven't played minecraft in years and tend to be busy on other projects. I could test/merge PRs if I get a free moment but you may find it easier to just maintain your fork and treat it as the main repo from now on.
